# Generated by Django 3.1.5 on 2022-05-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pace', models.TimeField()),
                ('bpm', models.IntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('run_time', models.TimeField()),
            ],
            options={
                'db_table': 'runlog',
            },
        ),
        migrations.CreateModel(
            name='RunTotalsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('furthest_distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_pace', models.TimeField()),
                ('fastest_pace', models.TimeField()),
                ('average_bpm', models.IntegerField()),
                ('average_runtime', models.TimeField()),
                ('goal', models.IntegerField()),
                ('yr', models.IntegerField()),
            ],
            options={
                'db_table': 'totals',
            },
        ),
    ]
