# Generated by Django 3.1.5 on 2022-03-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RunLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runlogmodel',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
